# Generated by Django 2.2.28 on 2023-05-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=200)),
                ('isfavorite', models.BooleanField()),
                ('date_adopted', models.DateField()),
                ('description', models.TextField()),
                ('attributes', models.TextField()),
                ('userid', models.CharField(max_length=100)),
            ],
        ),
    ]
